// Generate supabase-seed.sql from the curated seed data, so the DB starts out
// matching the live seed view. Run: node --experimental-strip-types scripts/gen-seed.ts > supabase-seed.sql
import { PROJECTS } from '../src/lib/data/projects.ts';

const q = (s: unknown) => "'" + String(s).replace(/'/g, "''") + "'";
const arr = (a: string[]) =>
	a.length ? 'array[' + a.map(q).join(', ') + ']::text[]' : "'{}'::text[]";

const lines: string[] = [
	'-- Seed the curated projects. Run once in the Supabase SQL editor AFTER',
	'-- supabase-schema.sql. Safe to re-run (on conflict do nothing). After this,',
	'-- edit everything in /admin. Generated by scripts/gen-seed.ts.',
	''
];

PROJECTS.forEach((p, i) => {
	lines.push(
		'insert into projects (id, title, summary, outcome, cluster, status, stack, schematic, github_url, year, sort_order, map_x, map_y, source) values (' +
			`${q(p.id)}, ${q(p.title)}, ${q(p.summary)}, ${arr(p.outcomes)}, ${q(p.cluster)}, ${q(p.status)}, ${arr(p.stack)}, ${arr(p.schematic)}, ${p.github ? q(p.github) : 'null'}, ${q(p.year)}, ${(i + 1) * 10}, ${p.x}, ${p.y}, 'manual')` +
			' on conflict (id) do nothing;'
	);
});

console.log(lines.join('\n'));
