// Generate supabase-seed.sql from the curated seed data, so the DB starts out
// (and stays) matching the live seed view. Run:
//   node --experimental-strip-types scripts/gen-seed.ts > supabase-seed.sql
//
// The insert upserts: on conflict it refreshes only the curated content
// (incl. the why/features showcase), and leaves live_url, loom_id and source
// untouched, since those are managed in /admin. So it is safe to re-run on a
// live DB to backfill new projects and content without clobbering edits.
import { PROJECTS } from '../src/lib/data/projects.ts';

const q = (s: unknown) => "'" + String(s).replace(/'/g, "''") + "'";
const arr = (a: string[]) =>
	a.length ? 'array[' + a.map(q).join(', ') + ']::text[]' : "'{}'::text[]";
const jsonb = (v: unknown) => q(JSON.stringify(v ?? [])) + '::jsonb';

const COLS = [
	'id', 'title', 'summary', 'why', 'features', 'outcome', 'cluster', 'status',
	'stack', 'schematic', 'github_url', 'year', 'sort_order', 'map_x', 'map_y', 'source'
];
// On conflict, refresh curated content only. Never touch id/source (identity)
// or live_url/loom_id (owner-managed in /admin, not in this insert at all).
const UPDATE_COLS = COLS.filter((c) => c !== 'id' && c !== 'source');

const lines: string[] = [
	'-- Seed the curated projects. Run once in the Supabase SQL editor AFTER',
	'-- supabase-schema.sql. Safe to re-run: on conflict it refreshes the curated',
	'-- content (incl. the why/features showcase) but leaves live_url, loom_id and',
	'-- source, which you manage in /admin. Generated by scripts/gen-seed.ts.',
	''
];

PROJECTS.forEach((p, i) => {
	const values = [
		q(p.id), q(p.title), q(p.summary), p.why ? q(p.why) : 'null', jsonb(p.features),
		arr(p.outcomes), q(p.cluster), q(p.status), arr(p.stack), arr(p.schematic),
		p.github ? q(p.github) : 'null', q(p.year), String((i + 1) * 10), String(p.x), String(p.y), "'manual'"
	];
	lines.push(
		`insert into projects (${COLS.join(', ')}) values (${values.join(', ')})\n` +
			`  on conflict (id) do update set ${UPDATE_COLS.map((c) => `${c} = excluded.${c}`).join(', ')};`
	);
});

console.log(lines.join('\n'));
