// Generated by the UI media integration tool from the finished media catalog.
// Do not edit by hand. Files live in public/_demos and are served by /demos/<file>.

export type DemoKind = 'app-demo' | 'system-walkthrough' | 'design-concept';

export interface Demo {
	id: string;
	url: string;
	poster: string;
	thumb: string;
	captions: string;
	durationSeconds: number;
	width: number;
	height: number;
	bytes: number;
	kind: DemoKind;
	caption: string;
}

export const DEMOS: Record<string, Demo> = {
	"quiz_funnel": {
		"id": "quiz_funnel",
		"url": "/demos/quiz_funnel.mp4",
		"poster": "/demos/quiz_funnel.webp",
		"thumb": "/demos/quiz_funnel-thumb.webp",
		"captions": "/demos/quiz_funnel.vtt",
		"durationSeconds": 23.2,
		"width": 1280,
		"height": 720,
		"bytes": 2477604,
		"kind": "system-walkthrough",
		"caption": "System walkthrough of the documented flow. Sample values, no product footage."
	},
	"video_landing": {
		"id": "video_landing",
		"url": "/demos/video_landing.mp4",
		"poster": "/demos/video_landing.webp",
		"thumb": "/demos/video_landing-thumb.webp",
		"captions": "/demos/video_landing.vtt",
		"durationSeconds": 20.7,
		"width": 1280,
		"height": 720,
		"bytes": 2296812,
		"kind": "system-walkthrough",
		"caption": "System walkthrough of the documented flow. Sample values, no product footage."
	},
	"video_product": {
		"id": "video_product",
		"url": "/demos/video_product.mp4",
		"poster": "/demos/video_product.webp",
		"thumb": "/demos/video_product-thumb.webp",
		"captions": "/demos/video_product.vtt",
		"durationSeconds": 21.5,
		"width": 1280,
		"height": 720,
		"bytes": 2711242,
		"kind": "system-walkthrough",
		"caption": "System walkthrough of the documented flow. Status on record: live in test mode."
	},
	"experience_engine": {
		"id": "experience_engine",
		"url": "/demos/experience_engine.mp4",
		"poster": "/demos/experience_engine.webp",
		"thumb": "/demos/experience_engine-thumb.webp",
		"captions": "/demos/experience_engine.vtt",
		"durationSeconds": 21.1,
		"width": 1280,
		"height": 720,
		"bytes": 2591460,
		"kind": "system-walkthrough",
		"caption": "System walkthrough of the documented flow. Deployment pending on record."
	},
	"dm_triage": {
		"id": "dm_triage",
		"url": "/demos/dm_triage.mp4",
		"poster": "/demos/dm_triage.webp",
		"thumb": "/demos/dm_triage-thumb.webp",
		"captions": "/demos/dm_triage.vtt",
		"durationSeconds": 22.1,
		"width": 1280,
		"height": 720,
		"bytes": 2907622,
		"kind": "design-concept",
		"caption": "Design concept from the discovery. No build exists; phase two is blocked."
	},
	"whatsapp_offer": {
		"id": "whatsapp_offer",
		"url": "/demos/whatsapp_offer.mp4",
		"poster": "/demos/whatsapp_offer.webp",
		"thumb": "/demos/whatsapp_offer-thumb.webp",
		"captions": "/demos/whatsapp_offer.vtt",
		"durationSeconds": 26.1,
		"width": 1280,
		"height": 720,
		"bytes": 3112946,
		"kind": "system-walkthrough",
		"caption": "Walkthrough of the documented flow plus the real photo-review screen. Messages, documents and links are simulated."
	},
	"booking_invoice": {
		"id": "booking_invoice",
		"url": "/demos/booking_invoice.mp4",
		"poster": "/demos/booking_invoice.webp",
		"thumb": "/demos/booking_invoice-thumb.webp",
		"captions": "/demos/booking_invoice.vtt",
		"durationSeconds": 31,
		"width": 1280,
		"height": 720,
		"bytes": 4568006,
		"kind": "app-demo",
		"caption": "Real wizard UI, de-branded, with synthetic data. Calendar, signature, payment, invoice and email are simulated."
	},
	"tq_chatbot": {
		"id": "tq_chatbot",
		"url": "/demos/tq_chatbot.mp4",
		"poster": "/demos/tq_chatbot.webp",
		"thumb": "/demos/tq_chatbot-thumb.webp",
		"captions": "/demos/tq_chatbot.vtt",
		"durationSeconds": 29.8,
		"width": 1280,
		"height": 720,
		"bytes": 4812652,
		"kind": "app-demo",
		"caption": "Real app in no-key mode: built-in mock replies and rule scoring, synthetic tenants and leads."
	},
	"grimoire": {
		"id": "grimoire",
		"url": "/demos/grimoire.mp4",
		"poster": "/demos/grimoire.webp",
		"thumb": "/demos/grimoire-thumb.webp",
		"captions": "/demos/grimoire.vtt",
		"durationSeconds": 36.7,
		"width": 1280,
		"height": 720,
		"bytes": 5882235,
		"kind": "app-demo",
		"caption": "Past project. Real dashboard with synthetic notes and a stand-in embedding provider."
	},
	"vault": {
		"id": "vault",
		"url": "/demos/vault.mp4",
		"poster": "/demos/vault.webp",
		"thumb": "/demos/vault-thumb.webp",
		"captions": "/demos/vault.vtt",
		"durationSeconds": 29,
		"width": 1280,
		"height": 720,
		"bytes": 4708918,
		"kind": "app-demo",
		"caption": "Real Vault UI on a synthetic fixture. The exchange rate shown in demos is a manual sample value."
	},
	"goatedtracking": {
		"id": "goatedtracking",
		"url": "/demos/goatedtracking.mp4",
		"poster": "/demos/goatedtracking.webp",
		"thumb": "/demos/goatedtracking-thumb.webp",
		"captions": "/demos/goatedtracking.vtt",
		"durationSeconds": 32.4,
		"width": 1280,
		"height": 720,
		"bytes": 3480448,
		"kind": "app-demo",
		"caption": "Real app with a synthetic herd on a local server."
	},
	"grece": {
		"id": "grece",
		"url": "/demos/grece.mp4",
		"poster": "/demos/grece.webp",
		"thumb": "/demos/grece-thumb.webp",
		"captions": "/demos/grece.vtt",
		"durationSeconds": 22.7,
		"width": 1280,
		"height": 720,
		"bytes": 2968864,
		"kind": "system-walkthrough",
		"caption": "Walkthrough of the repository code plus its real API with sample readings. No hardware footage."
	},
	"standup": {
		"id": "standup",
		"url": "/demos/standup.mp4",
		"poster": "/demos/standup.webp",
		"thumb": "/demos/standup-thumb.webp",
		"captions": "/demos/standup.vtt",
		"durationSeconds": 22.1,
		"width": 1280,
		"height": 720,
		"bytes": 4107568,
		"kind": "app-demo",
		"caption": "Real dashboard on fictional users served from a local cache. No GitHub calls."
	},
	"almanac": {
		"id": "almanac",
		"url": "/demos/almanac.mp4",
		"poster": "/demos/almanac.webp",
		"thumb": "/demos/almanac-thumb.webp",
		"captions": "/demos/almanac.vtt",
		"durationSeconds": 24.3,
		"width": 1280,
		"height": 720,
		"bytes": 3557253,
		"kind": "app-demo",
		"caption": "Real app on an in-browser data fixture with synthetic tasks and habits."
	},
	"asacafe": {
		"id": "asacafe",
		"url": "/demos/asacafe.mp4",
		"poster": "/demos/asacafe.webp",
		"thumb": "/demos/asacafe-thumb.webp",
		"captions": "/demos/asacafe.vtt",
		"durationSeconds": 22.3,
		"width": 1280,
		"height": 720,
		"bytes": 2954537,
		"kind": "app-demo",
		"caption": "Real app as a guest with generic sample cafes. Map tiles from OpenStreetMap."
	},
	"portfolio": {
		"id": "portfolio",
		"url": "/demos/portfolio.mp4",
		"poster": "/demos/portfolio.webp",
		"thumb": "/demos/portfolio-thumb.webp",
		"captions": "/demos/portfolio.vtt",
		"durationSeconds": 25,
		"width": 1280,
		"height": 720,
		"bytes": 3890971,
		"kind": "app-demo",
		"caption": "Local pre-release build of this site with its public project data."
	},
	"social": {
		"id": "social",
		"url": "/demos/social.mp4",
		"poster": "/demos/social.webp",
		"thumb": "/demos/social-thumb.webp",
		"captions": "/demos/social.vtt",
		"durationSeconds": 21.1,
		"width": 1280,
		"height": 720,
		"bytes": 2403678,
		"kind": "system-walkthrough",
		"caption": "System walkthrough of the documented publishing pipeline. Drafts drawn as placeholders."
	},
	"moajump": {
		"id": "moajump",
		"url": "/demos/moajump.mp4",
		"poster": "/demos/moajump.webp",
		"thumb": "/demos/moajump-thumb.webp",
		"captions": "/demos/moajump.vtt",
		"durationSeconds": 26.7,
		"width": 1280,
		"height": 720,
		"bytes": 2667125,
		"kind": "app-demo",
		"caption": "Real gameplay from the unmodified build. The leaderboard uses built-in mock scores."
	},
	"moisture": {
		"id": "moisture",
		"url": "/demos/moisture.mp4",
		"poster": "/demos/moisture.webp",
		"thumb": "/demos/moisture-thumb.webp",
		"captions": "/demos/moisture.vtt",
		"durationSeconds": 25.7,
		"width": 1280,
		"height": 720,
		"bytes": 4123438,
		"kind": "app-demo",
		"caption": "Real desktop app driven by a simulated device. Synthetic readings, no hardware footage."
	},
	"smartpot": {
		"id": "smartpot",
		"url": "/demos/smartpot.mp4",
		"poster": "/demos/smartpot.webp",
		"thumb": "/demos/smartpot-thumb.webp",
		"captions": "/demos/smartpot.vtt",
		"durationSeconds": 20.9,
		"width": 1280,
		"height": 720,
		"bytes": 2722763,
		"kind": "system-walkthrough",
		"caption": "Walkthrough of the repository code plus its real API with sample readings. The repo has no app screen."
	},
	"carwash": {
		"id": "carwash",
		"url": "/demos/carwash.mp4",
		"poster": "/demos/carwash.webp",
		"thumb": "/demos/carwash-thumb.webp",
		"captions": "/demos/carwash.vtt",
		"durationSeconds": 19.1,
		"width": 1280,
		"height": 720,
		"bytes": 1855990,
		"kind": "system-walkthrough",
		"caption": "System walkthrough of the documented flow. Sample job and amounts."
	}
};
